language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install  --prefer-dist --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - mombuartworks@gmail.com
    on_success: always
    on_failure: always

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-text